name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: croplify-webapp  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.9'              # set this to the Python version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Test with unittest
        run: |
          python test.py
        
